### ISSUE TITLE
Add OCI image support

### ISSUE THREAD

**Issue by wagoodman** [anchore/stereoscope#14]
Currently only supports docker images. The `github.com/google/go-containerregistry` dependency was specifically selected due to the OCI v1 interface abstraction, allowing for multiple providers of container image formats that mapped to OCI v1 features. Since all stereoscope features depend on this abstraction (and are not hard coded to any specific format) it should be a relatively easy lift to implement OCI support from multiple sources (directory, tar archives, etc).

**Comment by wagoodman** [comment]
Prototype for adding OCI support: https://github.com/anchore/stereoscope/compare/add-oci-support

**Comment by zhill** [comment]
How close do you feel that is @wagoodman ?

**Comment by wagoodman** [comment]
Very close, the `oci-archive` and `oci-directory` can be added to syft and grype with this branch. What's missing is fetching directly from an image source (such as podman) instead of the user needing to export the image manually from an image source then feed it into syft/grype.

**Comment by wagoodman** [comment]
just for safe keeping, the start of a prototype to pull in an OCI layout dir from containers/image lib https://github.com/anchore/stereoscope/tree/oci-containers-storage-lib . This will not work for us if we wish to keep our current CGO-less requirement.
