### ISSUE TITLE
Stereoscope cannot inspect images in Docker Desktop

### ISSUE THREAD

**Issue by Nicu-Ducal** [anchore/stereoscope#180]
Hello! 
I have created a custom Rabbit docker image and I wanted to check it for vulnerabilities using grype. The problem that I'm stuck now with is that grype does not identify my locally built image. For example, my custom image is named `custom-rabbit`, and when I call `grype custom-rabbit` I get the following errror:

```
grype custom-rabbit                                                             
 ✔ Vulnerability DB        [updated]
 ✔ Pulled image            
1 error occurred:
 * failed to catalog: could not fetch image "custom-rabbit": unable to use DockerDaemon source: pull failed: Error response from daemon: pull access denied for custom-rabbit, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

I have Docker running in the background, I have checked that it's up using `systemctl status docker` and also, my Docker Desktop app is running in the background. Yet, I haven't found a fix for it. Could you look up into this?

As with other images (ones from dockerhub) I have no problems with checking them, it's only the ones which are built locally.

**Environment**:
- Output of `grype version`: 0.61.1
- OS (e.g: `cat /etc/os-release` or similar): Ubuntu 22.04.2 LTS Jammy

**Comment by tgerla** [comment]
Hi @Nicu-Ducal, thanks for the report and the updates. We think it has to do with a new feature in Docker Desktop: specifically, being able to change which socket file is used to communicate with Docker Desktop. We will need to do some investigation to figure out what exactly is going on.

As a possible workaround can you go to your Docker Desktop settings and select Advanced, and select "Enable default Docker socket"?

**Comment by purujitgoyal** [comment]
Facing the same issue. Upgraded to v0.61.0 from v0.59.0 and started having this issue.

@tgerla the workaround is not working as well.

**Comment by Nicu-Ducal** [comment]
> As a possible workaround can you go to your Docker Desktop settings and select Advanced, and select "Enable default Docker socket"?

I think I have an older version of Docker Desktop, which doesn't even have this specific setting :( I can Update if you desire

**Comment by tgerla** [comment]
Possibly related to: https://github.com/anchore/grype/issues/1314

**Comment by spiffcs** [comment]
If there is an issue with Desktop Vs Service then it might have to do with how they treat the socket in the latest release:
https://github.com/anchore/syft/blob/main/DEVELOPING.md#docker-settings-for-getting-started

Check out these docs we just added which show how to setup the context and allow the default docker socket to be used - If there is anything different on linux as far as the desktop settings let me know and I can update the docs!

**Comment by tgerla** [comment]
HI @purujitgoyal and @Nicu-Ducal, we have made some updates to the way that we communicate with Docker Desktop in Syft 0.86 (included in the latest version of Grype) -- can you upgrade and see if you are still seeing problems?

**Comment by Nicu-Ducal** [comment]
Hi @tgerla! I'll give it a try maybe this weekend or on Tuesday, thanks for the notice!

**Comment by tgerla** [comment]
Hi @Nicu-Ducal, just checking to see if you are still having problems with this...happy to help out if you are still seeing issues!

**Comment by Nicu-Ducal** [comment]
Hey @tgerla! Sorry for ghosting you, just had a lot of work lately and didn't really had time to check it. I've tried now and it still seems to now see the images that were created by Docker Desktop Daemon :( It's okay though, because I've stopped using it and I'm just using the CLI daemon now and it works fine with it. 

P.S. It raises the same error as previously

**Comment by purujitgoyal** [comment]
Hey @tgerla, it's working for me now. I'm on v0.66.0.

**Comment by tgerla** [comment]
Thanks @purujitgoyal and @Nicu-Ducal for your responses. Nicu, I'll go ahead and close this issue but if you would ever like us to revisit it with you, please re-open this or find us on Slack and we will be happy to help!

**Comment by Nicu-Ducal** [comment]
Sure thing, thank you @tgerla for your help and input!
