### ISSUE TITLE
Goroutine Leak in Long-Running Services with Stereoscope

### ISSUE THREAD

**Issue by iAklis** [anchore/stereoscope#182]
**What happened**:
I've noticed a goroutine leak when using stereoscope in a service that needs to run continuously. The issue seems to be with connections to the Docker daemon via the Unix socket not being released.

**What you expected to happen**:
After continuously communicating with the Docker daemon, Stereoscope should not leave long connections unreleased.

**How to reproduce it (as minimally and precisely as possible)**:

Here's a minimal reproducible example:

```go
package main

import (
    "context"
    "fmt"
    "net/http"
    _ "net/http/pprof"
    "os"
    "os/signal"
    "syscall"

    "github.com/anchore/stereoscope/internal/log"
    "github.com/anchore/stereoscope/pkg/image"

    "github.com/anchore/stereoscope"
)

func main() {
    go func() {
        http.ListenAndServe(":6060", nil)
    }()

    signalChan := make(chan os.Signal, 1)
    signal.Notify(signalChan, os.Interrupt, syscall.SIGTERM)

    go func() {
        for {
            ctx := context.TODO()

            ImageSource := image.DockerDaemonSource
            UserInput := "busybox:latest"
            img, err := stereoscope.GetImageFromSource(ctx, UserInput, ImageSource)
            if err != nil {
                panic(err)
            }
            cleanup := func() {
                if err := img.Cleanup(); err != nil {
                    log.Warnf("unable to cleanup image=%q: %w", UserInput, err)
                }
            }

            for _, layer := range img.Layers {
                fmt.Printf("layer: %s\n", layer.Metadata.Digest)
            }

            cleanup()

        }
    }()

    <-signalChan

}
```
**Anything else we need to know?**:

**Environment**:
```
OS: Linux kaze 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Docker: 20.10.21 # installed by `sudo apt install docker.io`
Stereoscope: v0.0.0-...-e14bc44 (Latest as of May 22, 2023)
```

**Comment by kzantow** [comment]
Thanks for the report @iAklis. After looking at this issue a bit and your PR, it seems as though you've ascertained that the network connections are being held open, resulting in an increase in resource usage.

The current model creates a new docker client per `GetImageFromSource` calls.

I'm not sure adjusting the `IdleTimeout` is necessarily a fix, but rather a fix for a specific case with specific timing/etc.. A couple of alternative fixes we discussed:

* Allow the caller to manage the connection and pass it in to a sibling function to `GetImageFromSource`
* Ensure all client connections are closed when calling `img.Cleanup()`

I think these solutions are somewhat mutually exclusive, do you have any thoughts here?

We'll bring this up again next week with the team but in the meantime please feel free to comment if you're able.

**Comment by wagoodman** [comment]
@iAklis I agree with @kzantow here, I can update your PR to adjust it to cleanup the clients after the provider is used if you'd like? 

What isn't obvious about the timeout approach is that if someone is using the API and is delaying using of the provider after it's creation (say more than 10 seconds) then there should be non-obvious failures when attempting to use the object.

**Comment by iAklis** [comment]
@kzantow I'm sorry for my late reply. I agree with you that setting `IdleTimeout` is not an efficient and elegant way.
And it's redundant here. 
In my mind, per GetImageFromSource calls own its daemon client and don't share it with others.

After looking at @wagoodman 's patch, I think his solution is better.

Thank @wagoodman and @kzantow .
