### ISSUE TITLE
increase max layer/file size from 2GB

### ISSUE THREAD

**Issue by 2rigor** [anchore/stereoscope#311]
**What would you like to be added**:
Support for layers above 2GB

**Why is this needed**:
Syft fails for such images

**Additional context**:
It happens due to [hard-coded](https://github.com/anchore/stereoscope/blob/main/pkg/file/tarutil.go#L17) threshold.
Apparently in [syft ](https://github.com/anchore/syft/blob/main/internal/file/copy.go#L9) there is also a limit for tar/zip files size, but I think it's less likely to happen.

One of the options is to make this limit configurable or at least to increase it e.g. to 20GB.

**Comment by kzantow** [comment]
After a number of tries: https://github.com/anchore/stereoscope/releases/tag/v0.0.8

**Comment by 2rigor** [comment]
thank you!
