### ISSUE TITLE
Add containerd support

### ISSUE THREAD

**Issue by wagoodman** [anchore/stereoscope#67]
In the same vein of supporting other container runtimes, it would be ideal to support pulling images from containerd directly.

**Comment by richotaylor** [comment]
Just wanted to add a +1 to this, just spent a few hours running into https://github.com/anchore/syft/issues/1048 without knowing it. I'm running Rancher Desktop locally which uses containerd by default.  Thanks!

**Comment by mabilgen** [comment]
Hey All,
The  the issue ([syft is unable to locate image locally in k8s with containerd runtime anchore/syft#1048](https://github.com/anchore/syft/issues/1048) ) is still there sfyt 1.19.0 I tested but no luck
