### ISSUE TITLE
Add podman support

### ISSUE THREAD

**Issue by wagoodman** [anchore/stereoscope#7]
- Add `podman` image source, enabling `podman:<image>` parsing
- Add `podman` image provider, enabling tarball extraction from the podman ~via it's varlink api~

**Comment by jonasagx** [comment]
podman's libpod uses CGO: https://github.com/containers/podman/blob/main/libpod/lock/shm/shm_lock.go#L5

**Comment by jonasagx** [comment]
Another way to support podman is through a docker client. Podman is docker-compatible making docker podman-compatible :)  

A docker client can use podman to work, however it needs an ssh tunnel. Syft looks for `DOCKER_HOST` while setting its docker client.

The process looks like: Syft --> Docker client --> podman daemon --> image pull.

Proof of dockerCLI<-->podman compatibility:
```sh
// start podman daemon AND make sure docker daemon is not running
$ podman machine start

// check its connection port
$ podman system connection ls
Name                         Identity                                  URI
podman-machine-default*      /Users/user/.ssh/podman-machine-default  ssh://core@localhost:[PORT]/run/user/1000/podman/podman.sock
podman-machine-default-root  /Users/user/.ssh/podman-machine-default  ssh://root@localhost:[PORT]/run/podman/podman.sock

// make a tunnel to podman socket
$ ssh -nNT -L/tmp/podman.sock:/run/user/1000/podman/podman.sock -i ~/.ssh/podman-machine-default ssh://core@localhost:[PORT]

// on another terminal 
$ export DOCKER_HOST=unix:///tmp/podman.sock
$ docker version // server should be a podman engine

// explicitly tell syft to use docker daemon 
$ syft docker:alpine:latest -vv
...
[0000] DEBUG image: source=DockerDaemon location=alpine:latest from-lib=stereoscope
...
```

I am not sure why the tunnel is necessary since the socket file is in the same file system of the host. Also dropping the tunnel reduces complexity.

**Comment by jonasagx** [comment]
![podman-ssh-tunnel](https://user-images.githubusercontent.com/774704/140463676-9d16b907-51df-488b-bf34-2534bab55982.png)[1]

Podman uses a tunnel to handle communication with its daemon. That is why the tunnel above was necessary, and why for stereoscope to talk to podman we should have a param to pass an ssh key.

[1] - https://www.redhat.com/sysadmin/podman-clients-macos-windows

**Comment by jonasagx** [comment]
Docker client has an option to customize the ssh call made during each request:
```golang
			if sshKeyPath := os.Getenv("PODMAN_SSH_KEY_PATH"); sshKeyPath != "" {
				helper, err = connhelper.GetCommandConnectionHelper("ssh", "-i", sshKeyPath, "-l", "core", "-p", "63753", "--", "localhost")	
```

error:
```sh
~/code/stereoscope/examples(main ✗) go run basic.go docker:alpine:latest -vv
DEBU[0000] image: source=DockerDaemon location=alpine:latest
panic: unable to inspect existing image: error during connect: Get "http://docker/v1.24/images/alpine:latest/json": net/http: HTTP/1.x transport connection broken: malformed HTTP status code "CoreOS"

goroutine 1 [running]:
main.main()
        stereoscope/examples/basic.go:29 +0x5f3
exit status 2
```

That connection worked, however http client is hitting the wrong address, if I can fix we are one step closer to integrating podman via the golang docker cli

**Comment by jonasagx** [comment]
Code changes available on https://github.com/jonasagx/stereoscope/

**Comment by luhring** [comment]
We'll set this aside for the time being, but we'll come back to it before too long!
